apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: canary-health
    failureLimit: 0
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - name: check
                image: curlimages/curl:8.10.1
                command: ["/bin/sh", "-c"]
                args:
                - |
                  color=$(curl -s http://demo-app-canary.demo.svc.cluster.local/color)
                  echo "Couleur detectee: $color"
                  echo "$color" | grep -qi "red" && exit 1
                  exit 0
              restartPolicy: Never
